- hosts: all
  remote_user: ansibleuser
  become: yes
  vars_files:
    - vars/main.yml
    - [ "vars/{{ ansible_facts['os_family'] }}.yml" ]

  roles:
    - role: wordpress 
    - role: geerlingguy.mysql
    