- name: Print My Os Family
  ansible.builtin.debug:
    var: ansible_os_family

- name: Print My Distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Remove all Installed PHP Packages
  ansible.builtin.package:
    name: php*
    state: absent

- name: Upgrade all packages
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install PHP prerequisite Packages (CentOS)
  ansible.builtin.yum:
    name: 
      - epel-release
      - yum-utils
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Disable all remi-php Repos (CentOS)
  ansible.builtin.command: yum-config-manager --disable remi-php*
  when: ansible_distribution == "CentOS"

- name: Enable Remi-Repo74 (CentOS)
  ansible.builtin.command: yum-config-manager --enable remi-php74
  when: ansible_distribution == "CentOS"

- name: Install Packages for wordpress
  ansible.builtin.package:
    name: 
      - '{{ apache_lib }}'
      - php
      - php-pear
      - php-cgi
      - php-common
      - php-curl
      - php-mbstring
      - php-gd
      - php-mysqlnd
      - php-bcmath
      - php-json
      - php-xml
      - php-intl
      - php-zip
      - php-imap
    update_cache: yes

- name: Enable service apache and ensure it is not masked
  ansible.builtin.systemd:
    name: '{{ apache_lib }}'
    enabled: true
    masked: no
    state: started

- name: Unarchive wordpress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes
    owner: '{{ apache_user }}'
    group: '{{ apache_user }}'
    extra_opts: [--strip-components=1]

- name: Update Config  
  template:  
    src: wp-config.php.j2  
    dest: /var/www/html/wp-config.php
  
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /var/www/html
    owner: '{{ apache_user }}'
    group: '{{ apache_user }}'
    mode: u=rwX,g=rwX,o=rX 
    recurse: true
    state: directory

- name: remove old index
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Enable .htaccess files in Apache config
  ansible.builtin.replace:
    path:  '{{ apache_config_file }}'
    after: '<Directory *"*/var/www/*"*>'
    before: '</Directory>'
    regexp: 'AllowOverride None'
    replace: AllowOverride All
  notify:
    - restart apache

- name: Create a symbolic link for mod_headers (Only Ubuntu)
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify:
    - restart apache
  when: ansible_os_family == "Debian"

- name: Install Packages for manage firewalld (CentOS)
  ansible.builtin.package:
    name: 
      - python-firewall
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Permit traffic in default zone for http service (CentOS)
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  when: ansible_os_family == "RedHat"

- name: Permit traffic in default zone for http service (Ubuntu)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_os_family == "Debian"